### ISSUE TITLE
question about docker and linkwarden

### ISSUE THREAD

**Issue by yellowbikewithbluehandles** [gardner/docker-aws-ses-postfix-relay#4]
Hello sorry about asking a question here because its the only place I found that I could contact you. There might be a better place to ask that I can't think of so I'm sorry I'm a idiot. 
What I wanted to talk to you about was docker and linkwarden because I am a new user of docker and don't really understand whats going on to well and I downloaded it to use linkwarden and found you in the registry. What I found confusing was your registry is the only one there but the name isn't the same as the github author for linkwarden and its over 2 years old. I was following a youtube video and thats why I was looking for linkwarden unders docker container manager registries. Is it safe to download from registries? How do I know if something is malicious and if I compromised my docker nas.
Am I doing something wrong? Is this not how I should be downloading linkwarden?
I also tried going to your about.me page for your repo but it redirected to httpsgithub.com which apparently is a malicious site ><.
I don't know what I am doing wrong haha it feels like every time I look up something and follow it I go down a strange hole where everything becomes more confusing and I realize I am even dumber then I realized.
I also realize it seems strange to ask someone if their registry thing and also website is malicious but for some strange reason I feel like I can trust you haha and I'm just doing something wrong and might be the perfect person to ask to learn more about docker and linkwarden about whats malicious or not. Thank you for reading :).

**Comment by gardner** [comment]
Hi there,
  A long time ago, I had worked with the author of linkwarden to help create a docker deployment. Back then, the project was nascent and wasn't quite ready for an official docker image. I had pushed a docker image to docker hub to show how it could work, but the project didn't adopt a docker workflow until later, after I had moved on. 

Today, it looks like the best way to get a docker container now is to clone the project and build it yourself. I hope that helps.

Cheers
